## Importing Necessary Libraries

In [35]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
import nltk

In [3]:
paragraph = """"Thank you very much, everybody. And congratulations to the class of 2017. That’s some achievement.This is your day and you’ve earned every minute of it. And I’m thrilled to be back at Liberty University. I’ve been here, this is now my third time. And we love setting records, right? We always set records. We have to set records, we have no choice.It’s been a little over a year since I’ve spoken on your beautiful campus and so much has changed. Right here, the class of 2017, dressed in cap and gown, graduating to a totally brilliant future. And here I am standing before you as president of the United States. So I’m guessing there are some people here today who thought that either one of those things, either one, would really require major help from God. Do we agree? And we got it.But here we are celebrating together on this very joyous occasion. And there is no place in the world I’d rather be to give my first commencement address as president than here with my wonderful friends at Liberty University.And I accepted this invitation a long time ago. I said to Jerry that I’d be there, and when I say something I mean it."""

In [4]:
sentences = nltk.sent_tokenize(paragraph)  # this is to convert paragraph into sentences

In [5]:
sentences

['"Thank you very much, everybody.',
 'And congratulations to the class of 2017.',
 'That’s some achievement.This is your day and you’ve earned every minute of it.',
 'And I’m thrilled to be back at Liberty University.',
 'I’ve been here, this is now my third time.',
 'And we love setting records, right?',
 'We always set records.',
 'We have to set records, we have no choice.It’s been a little over a year since I’ve spoken on your beautiful campus and so much has changed.',
 'Right here, the class of 2017, dressed in cap and gown, graduating to a totally brilliant future.',
 'And here I am standing before you as president of the United States.',
 'So I’m guessing there are some people here today who thought that either one of those things, either one, would really require major help from God.',
 'Do we agree?',
 'And we got it.But here we are celebrating together on this very joyous occasion.',
 'And there is no place in the world I’d rather be to give my first commencement address as

#### now we have to convert sentences into words

In [7]:
word = nltk.word_tokenize(paragraph)

In [8]:
word

['``',
 'Thank',
 'you',
 'very',
 'much',
 ',',
 'everybody',
 '.',
 'And',
 'congratulations',
 'to',
 'the',
 'class',
 'of',
 '2017',
 '.',
 'That',
 '’',
 's',
 'some',
 'achievement.This',
 'is',
 'your',
 'day',
 'and',
 'you',
 '’',
 've',
 'earned',
 'every',
 'minute',
 'of',
 'it',
 '.',
 'And',
 'I',
 '’',
 'm',
 'thrilled',
 'to',
 'be',
 'back',
 'at',
 'Liberty',
 'University',
 '.',
 'I',
 '’',
 've',
 'been',
 'here',
 ',',
 'this',
 'is',
 'now',
 'my',
 'third',
 'time',
 '.',
 'And',
 'we',
 'love',
 'setting',
 'records',
 ',',
 'right',
 '?',
 'We',
 'always',
 'set',
 'records',
 '.',
 'We',
 'have',
 'to',
 'set',
 'records',
 ',',
 'we',
 'have',
 'no',
 'choice.It',
 '’',
 's',
 'been',
 'a',
 'little',
 'over',
 'a',
 'year',
 'since',
 'I',
 '’',
 've',
 'spoken',
 'on',
 'your',
 'beautiful',
 'campus',
 'and',
 'so',
 'much',
 'has',
 'changed',
 '.',
 'Right',
 'here',
 ',',
 'the',
 'class',
 'of',
 '2017',
 ',',
 'dressed',
 'in',
 'cap',
 'and',
 'gown

## Now we are doing stemming, let see how we can do that

In [9]:
from nltk.stem import PorterStemmer

In [10]:
from nltk.corpus import stopwords


In [11]:
stemmer = PorterStemmer()

In [12]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

### Now we will remove the words from the above sentences which are present in (corpus stopwords) and then do stemming

In [13]:
for i in range (len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [stemmer.stem(word) for word in words if word not in set( stopwords.words('english'))]
    sentences[i] = ' '.join(words)

### Now lets try to do Lemmitization on our sentences

In [14]:
from nltk.stem import WordNetLemmatizer

In [15]:
lemmatizer = WordNetLemmatizer()

In [16]:
for i in range (len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [lemmatizer.lemmatize(word) for word in words if word not in set( stopwords.words('english'))]
    sentences[i] = ' '.join(words)

## Now applying TF-IDF

### Cleaning the text

In [17]:
import re

In [18]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [19]:
ps = PorterStemmer()
wordnet = WordNetLemmatizer()
sentences = nltk.sent_tokenize(paragraph)
corpus = []
for i in range (len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [20]:
corpus

['thank much everybodi',
 'congratul class',
 'achiev day earn everi minut',
 'thrill back liberti univers',
 'third time',
 'love set record right',
 'alway set record',
 'set record choic littl year sinc spoken beauti campu much chang',
 'right class dress cap gown graduat total brilliant futur',
 'stand presid unit state',
 'guess peopl today thought either one thing either one would realli requir major help god',
 'agre',
 'got celebr togeth joyou occas',
 'place world rather give first commenc address presid wonder friend liberti univers accept invit long time ago',
 'said jerri say someth mean']

#### Stemming is not giving any proper insights of sentences....lets try with lemmatizer

In [21]:
ps = PorterStemmer()
wordnet = WordNetLemmatizer()
sentences = nltk.sent_tokenize(paragraph)
corpus = []
for i in range (len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review = review.lower()
    review = review.split()
    review = [wordnet.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [22]:
corpus

['thank much everybody',
 'congratulation class',
 'achievement day earned every minute',
 'thrilled back liberty university',
 'third time',
 'love setting record right',
 'always set record',
 'set record choice little year since spoken beautiful campus much changed',
 'right class dressed cap gown graduating totally brilliant future',
 'standing president united state',
 'guessing people today thought either one thing either one would really require major help god',
 'agree',
 'got celebrating together joyous occasion',
 'place world rather give first commencement address president wonderful friend liberty university accepted invitation long time ago',
 'said jerry say something mean']

## Lets now create Bag of Word (BOW) model

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x  = cv.fit_transform(corpus).toarray()

In [24]:
print (x)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 1 ... 1 0 0]
 [0 0 0 ... 0 0 0]]


In [25]:
x.shape

(15, 78)

In [26]:
x.size

1170

In [27]:
a = 31* 114

In [28]:
a

3534

### Now lets try to implement TF-IDF

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [30]:
tf = TfidfVectorizer()

In [31]:
x = tf.fit_transform(corpus).toarray()

In [32]:
print(x)

[[0.        0.        0.        ... 0.        0.        0.       ]
 [0.        0.        0.        ... 0.        0.        0.       ]
 [0.        0.4472136 0.        ... 0.        0.        0.       ]
 ...
 [0.        0.        0.        ... 0.        0.        0.       ]
 [0.2498751 0.        0.2498751 ... 0.2498751 0.        0.       ]
 [0.        0.        0.        ... 0.        0.        0.       ]]
